django-day-3-example/django_example_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

django-day-3-example/posts/urls.py
from django.urls import path

from posts.views import index, retrieve, create_comment, api_posts

app_name = 'posts'
urlpatterns = [
    path('', index, name="index"),
    path('<int:id>', retrieve, name="retrieve"),
    path('create_comment/<int:id>', create_comment, name="create_comment"),
    path('api', api_posts),
]

django-day-3-example/posts/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampedModel):
    title = models.CharField(max_length=128)
    body = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


class Comment(TimeStampedModel):
    body = models.CharField(max_length=512)

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    class Meta:
        ordering = ['-created_at']

django-day-3-example/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response

from posts.models import Post, Comment
from posts.serializers import PostSerializer

def index(request):
    posts = Post.objects.all()
    return render(request, 'posts/index.html', {'posts': posts})

def retrieve(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'posts/retrieve.html', {'post': post})

def create_comment(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == "POST":
        comment = Comment()
        comment.body = request.POST['body']
        comment.post = post
        comment.save()
    
    return redirect('posts:retrieve', id=post.id)


@api_view(['GET'])
def api_posts(requests):
    posts = Post.objects.all()
    payload = PostSerializer(posts, many=True)

    return Response(data=payload.data)

django-day-3-example/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Posts{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    <style>
        .post {
            margin-bottom: 2rem;
        }
        .title {
            font-weight: bold;
            margin-bottom: 1rem;
            font-size: 18px;
        }
        .body {
            padding: 1rem;
        }
        .comment {
            margin-bottom: 2rem;
        }
    </style>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

django-day-3-example/templates/posts/index.html
{% extends "layout.html" %}

{% block content %}
<h1>All Posts</h1>

{% for post in posts %}
<div class="post">
    <div class="title">
        <a href="{% url 'posts:retrieve' id=post.id %}">{{ post.title }}</a>
    </div>
    <div class="body">
        {{ post.body }}
    </div>
</div>
{% endfor %}
{% endblock content %}

django-day-3-example/templates/posts/retrieve.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <div>
        Created at: {{ post.created_at }}
    </div>
    <div>
        <p>
            {{ post.body }}
        </p>
    </div>

    <div>
        <form method="POST" action="{% url 'posts:create_comment' id=post.id %}">
            {% csrf_token %}
            <div><textarea name="body" cols="50"></textarea></div>
            <div><button>Add Comment</button></div>
        </form>
    </div>

    <div>
        <h5>Comments</h5>
    {% for comment in post.comments.all %}
        <div class="comment">
            <div>{{ comment.body }}</div>
            <div><strong>{{ comment.created_at }}</strong></div>
        </div>
    {% empty %}
        <p><em>No Comments</em></p>
    {% endfor %}
    </div>
{% endblock content %}  